name: Deploy to server on push
on:
  push:
    branches: [Film-PC]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy via SSH (run git pull & build)
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || '22' }}
          script: |
            set -e
            cd /var/www/your-app-folder   # เปลี่ยนเป็น path จริงบน server
            git fetch --all
            git reset --hard origin/main
            # ตัวอย่าง Node.js build
            npm ci
            npm run build
            pm2 restart all || pm2 start ecosystem.config.js
