name: Enable auto-merge for PRs
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  enable-automerge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Enable auto-merge via REST API
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            if (!pr || pr.draft) {
              console.log('No PR or draft — skip');
              return;
            }
            await github.request('PUT /repos/{owner}/{repo}/pulls/{pull_number}/auto-merge', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              merge_method: 'squash' // หรือ 'merge' / 'rebase'
            });
            console.log(`Enabled auto-merge for PR #${pr.number}`);
